# Generated by Django 4.1.7 on 2023-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_remove_mentor_menteeage_remove_mentor_menteename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
