# Generated by Django 4.1.7 on 2023-04-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor')], default='mentee', max_length=6),
        ),
    ]
