# Generated by Django 4.1.7 on 2023-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mentee_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_mentee',
            field=models.BooleanField(verbose_name='is mentee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(verbose_name='is mentor'),
        ),
    ]
