# Generated by Django 4.1.7 on 2023-04-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_mentee_alter_user_is_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
