# Generated by Django 4.1.7 on 2023-03-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_mento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mento',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='interests',
        ),
    ]
