# Generated by Django 4.1.7 on 2023-03-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_delete_mento_remove_mentee_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='campus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentee',
            name='interests',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
