# Generated by Django 4.1.7 on 2023-03-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='menteeage',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='menteename',
        ),
        migrations.AddField(
            model_name='mentee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentee',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
