# Generated by Django 4.1.7 on 2023-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_remove_mentee_campus_remove_mentee_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
